### ISSUE TITLE
Index out of range in find_taint_sinks.py

### ISSUE THREAD

**Issue by InfectedPacket** [ucsb-seclab/BootStomp#3]
The following was exception was raised when executing `find_taint.py` from IDA 6.8:

```
list index out of range
Traceback (most recent call last):
  File "D:\software\IDA 6.8\python\idaapi.py", line 541, in IDAPython_ExecScript
    execfile(script, g)
  File "D:/src/BootStomp-master/taint_analysis/find_taint.py", line 29, in <module>
    get_taint_sink_memcpy.get_sinks()
  File "D:/src/BootStomp-master/taint_analysis\find_taint_sinks.py", line 183, in get_sinks
    self.list_potential_memcpy()
  File "D:/src/BootStomp-master/taint_analysis\find_taint_sinks.py", line 91, in list_potential_memcpy
    function_info = helper.functions_info[function_index]
IndexError: list index out of range
```

This exception is raised in the following code segment:

```
    def list_potential_memcpy(self):
        global functions_info
        for function_index in xrange(self.top_xref_limit):
            function_info = helper.functions_info[function_index]
            ...
```

In this case, the ```self.top_xref_limit``` is set to 50, however the exception is raised when ```function_index``` reaches 29, which appears to indicate that ```self.top_xref_limit``` is kept to the default value of 50 set in the constructor of ```GetTaintSink```:

```
    def __init__(self, top_xref_limit = 50, min_arg_cnt = 2, max_arg_cnt = 3, interfunction_level = 1, max_bb_size = 8, max_call_count = 3):
        self.memcpy_like_functions = []
        self.taint_sinks = []
        self.top_xref_limit = top_xref_limit
        ...
```

Without having look at the entirety of the code, it seems that the ```for...loop``` should be as follow:

```
    def list_potential_memcpy(self):
        global functions_info
        for function_index in xrange(0, len(helper.functions_info)):
             ...
```

Thanks for your research. very interesting.

**Comment by dipanjan** [comment]
@InfectedPacket Do you have the binary you used lying around?

**Comment by dipanjan** [comment]
No response, hence closing this issue.
