### ISSUE TITLE
angr.errors.SimEngineError: No bytes in memory for block starting at *addr*

### ISSUE THREAD

**Issue by ramhillel** [ucsb-seclab/BootStomp#5]
When trying to run bootloadertaint.py on the samples bootloaders and config files I get the same error:

(angr) [10:10:04] Ram-MacBook-Pro:BootStomp ramhillel$ python taint_analysis/bootloadertaint.py config/config.hboot 
WARNING | 2017-10-10 10:10:07,511 | cle.blob | No custom_entry_point was specified for blob, assuming 0
Deprecation warning: Use main_object instead of main_bin
Traceback (most recent call last):
  File "taint_analysis/bootloadertaint.py", line 330, in <module>
    bt.run()
  File "taint_analysis/bootloadertaint.py", line 271, in run
    self._preprocess_taint_file()
  File "taint_analysis/bootloadertaint.py", line 199, in _preprocess_taint_file
    line = patch_fucking_idapython(line, base_addr)
  File "taint_analysis/bootloadertaint.py", line 155, in patch_fucking_idapython
    bl = self._p.factory.block(int(call_addr, 16) - base_addr, thumb=True)
  File "/Users/admin/code/.virtualenvs/angr/lib/python2.7/site-packages/angr/factory.py", line 308, in block
    backup_state=backup_state, opt_level=opt_level, num_inst=num_inst, traceflags=traceflags
  File "/Users/admin/code/.virtualenvs/angr/lib/python2.7/site-packages/angr/block.py", line 60, in __init__
    traceflags=traceflags)
  File "/Users/admin/code/.virtualenvs/angr/lib/python2.7/site-packages/angr/engines/vex/engine.py", line 462, in lift
    raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
**angr.errors.SimEngineError: No bytes in memory for block starting at 0x70076c44.**

The same happens for each of the config files.
angr and all of its dependencies were installed without any issues.

Thanks,

**Comment by ramhillel** [comment]
After some digging, find out that installing older versions of angr and its dependencies solved that issue.

**Comment by ltfish** [comment]
> find out that installing older versions of angr and its dependencies solved that issue.

I'm aware that the mega refactor we had in angr impacted BootStomp. We are not sure if or when we are going to resolve this issue. The best workaround right now is to install an old version of angr.

**Comment by zardus** [comment]
It might be a good idea to have a Dockerfile, based on `angr/angr`, that checks out the right commits from the various repos (cc @badnack).
