### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by snx90** [ucsb-seclab/BootStomp#8]
Hi there,

When trying to reproduce the example for huawei p8 I am getting the following error:

<pre><code>~/Development/bootstomp/BootStomp$ python taint_analysis/bootloadertaint.py config/config.huawei
WARNING | 2018-03-08 16:11:06,322 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
WARNING | 2018-03-08 16:11:06,344 | cle.blob | No custom_entry_point was specified for blob /home/santitox/Development/bootstomp/BootStomp/bootloaders/huawei_p8/fastboot.img, assuming 0
WARNING | 2018-03-08 16:11:06,344 | cle.blob | No custom_base_addr was specified for blob /home/santitox/Development/bootstomp/BootStomp/bootloaders/huawei_p8/fastboot.img, assuming 0
Deprecation warning: Use main_object instead of main_bin
Traceback (most recent call last):
  File "taint_analysis/bootloadertaint.py", line 330, in <module>
    bt.run()
  File "taint_analysis/bootloadertaint.py", line 271, in run
    self._preprocess_taint_file()
  File "taint_analysis/bootloadertaint.py", line 199, in _preprocess_taint_file
    line = patch_fucking_idapython(line, base_addr)
  File "taint_analysis/bootloadertaint.py", line 155, in patch_fucking_idapython
    bl = self._p.factory.block(int(call_addr, 16) - base_addr, thumb=True)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 332, in block
    backup_state=backup_state, opt_level=opt_level, num_inst=num_inst, traceflags=traceflags
  File "/usr/local/lib/python2.7/dist-packages/angr/block.py", line 60, in __init__
    traceflags=traceflags)
  File "/usr/local/lib/python2.7/dist-packages/angr/engines/vex/engine.py", line 461, in lift
    raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
angr.errors.SimEngineError: No bytes in memory for block starting at 0x7002ec8.
</code></pre>

This issue does not happen when running within the docker container provided. Yet, in both scenarios, trying to manually load the bootloader with angr returns a different error message:

<pre><code>~/Development/bootstomp/BootStomp$ python
Python 2.7.13 (default, Nov 23 2017, 15:37:09) 
[GCC 6.3.0 20170406] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
WARNING | 2018-03-08 16:26:21,362 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
>>> p = angr.Project("bootloaders/huawei_p8/fastboot.img")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 164, in __init__
    self.loader = cle.Loader(self.filename, **load_options)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 126, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *force_load_libs)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 493, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 583, in _load_object_isolated
    raise CLECompatibilityError("Unable to find a loader backend for %s.  Perhaps try the 'blob' loader?" % spec)
cle.errors.CLECompatibilityError: Unable to find a loader backend for bootloaders/huawei_p8/fastboot.img.  Perhaps try the 'blob' loader?
</code></pre>

**Comment by dipanjan** [comment]
We advise you to use docker-ed version of the tool. When loading the BLOB manually, you are not passing the appropriate switches as the tool uses here: [https://github.com/ucsb-seclab/BootStomp/blob/master/taint_analysis/bootloadertaint.py#L44](https://github.com/ucsb-seclab/BootStomp/blob/master/taint_analysis/bootloadertaint.py#L44)
